// <auto-generated />
using System;
using App.Infra.Db.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infra.Db.SqlServer.Migrations
{
    [DbContext(typeof(MayneDbContext))]
    [Migration("20250504131611_edit")]
    partial class edit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Core.Mayne.Base.Entities.Base", b =>
                {
                    b.Property<int>("BaseNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaseNumber"));

                    b.Property<string>("BaseAdrress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaseId")
                        .HasColumnType("int");

                    b.Property<string>("BaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.HasKey("BaseNumber");

                    b.HasIndex("CityId");

                    b.ToTable("Bases", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.Cars.Entities.Car", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int?>("BaseNumber")
                        .HasColumnType("int");

                    b.Property<string>("CarBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarOwnerID")
                        .HasColumnType("int");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarId");

                    b.HasIndex("BaseNumber");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.City.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.History.Entites.CarHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("IssueReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Reservation")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.HasIndex("CarId");

                    b.ToTable("CarHistory", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.Reservation.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReservationCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.User.Entities.Operator", b =>
                {
                    b.Property<int>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperatorId"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OperatorId");

                    b.ToTable("Operators", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.User.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.User.Entities.Costomer", b =>
                {
                    b.HasBaseType("App.Domain.Core.Mayne.User.Entities.User");

                    b.ToTable("Costomers", (string)null);
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.Base.Entities.Base", b =>
                {
                    b.HasOne("App.Domain.Core.Mayne.City.Entities.City", "City")
                        .WithMany("Bases")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.Cars.Entities.Car", b =>
                {
                    b.HasOne("App.Domain.Core.Mayne.Base.Entities.Base", null)
                        .WithMany("Cars")
                        .HasForeignKey("BaseNumber");

                    b.HasOne("App.Domain.Core.Mayne.Reservation.Entities.Reservation", "reserve")
                        .WithOne("Car")
                        .HasForeignKey("App.Domain.Core.Mayne.Cars.Entities.Car", "CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Mayne.User.Entities.Costomer", "CarOwner")
                        .WithMany("CostomerCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarOwner");

                    b.Navigation("reserve");
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.History.Entites.CarHistory", b =>
                {
                    b.HasOne("App.Domain.Core.Mayne.Base.Entities.Base", "ResevedBase")
                        .WithMany()
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Mayne.Cars.Entities.Car", "Car")
                        .WithMany("CarHistory")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("ResevedBase");
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.Reservation.Entities.Reservation", b =>
                {
                    b.HasOne("App.Domain.Core.Mayne.Base.Entities.Base", "Base")
                        .WithMany("DailyReservations")
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Base");
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.User.Entities.Costomer", b =>
                {
                    b.HasOne("App.Domain.Core.Mayne.User.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("App.Domain.Core.Mayne.User.Entities.Costomer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.Base.Entities.Base", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("DailyReservations");
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.Cars.Entities.Car", b =>
                {
                    b.Navigation("CarHistory");
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.City.Entities.City", b =>
                {
                    b.Navigation("Bases");
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.Reservation.Entities.Reservation", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Core.Mayne.User.Entities.Costomer", b =>
                {
                    b.Navigation("CostomerCars");
                });
#pragma warning restore 612, 618
        }
    }
}
